STOCK_BUY = 23
STOCK_SELL = 24
FIX_PRICE = 11
LATEST_PRICE = 5

ORDER_UNREPORTED = 48
ORDER_WAIT_REPORTING = 49
ORDER_REPORTED = 50
ORDER_REPORTED_CANCEL = 51
ORDER_PART_SUCC_CANCEL = 52
ORDER_PART_CANCEL = ORDER_PART_SUCC_CANCEL
ORDER_CANCELED = 53
ORDER_PART_SUCC = 54
ORDER_SUCCEEDED = 55
ORDER_JUNK = 57
